// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Datamatiker2SemExam.Models;

public partial class Bil
{
    public int Id { get; set; }

    public string Nummerplade { get; set; }

    public string Model { get; set; }

    public int PrisPrDag { get; set; }

    public virtual ICollection<Leje> Lejes { get; set; } = new List<Leje>();
}