// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Datamatiker2SemExam.Models;

public partial class Booking
{
    public int Id { get; set; }

    public byte[] StartTime { get; set; }

    public double? Duration { get; set; }

    public int TreatmentId { get; set; }

    public int CustomerId { get; set; }

    public int WorkerId { get; set; }
}