// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Datamatiker2SemExam.Models;

public partial class Kunde
{
    public int Id { get; set; }

    public string Navn { get; set; }

    public int Telefon { get; set; }

    public bool Vip { get; set; }

    public virtual ICollection<Leje> Lejes { get; set; } = new List<Leje>();
}