// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Datamatiker2SemExam.Models;

public partial class Leje
{
    public int Id { get; set; }

    public int KundeId { get; set; }

    public int BilId { get; set; }

    public DateOnly Dato { get; set; }

    public int AntalDage { get; set; }

    public virtual Bil Bil { get; set; }

    public virtual Kunde Kunde { get; set; }
}