// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Datamatiker2SemExam.Models;

public partial class OpeningHour
{
    public int Id { get; set; }

    public string Day { get; set; }

    public string StartTime { get; set; }

    public string EndTime { get; set; }

    public bool? Open { get; set; }
}