// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Datamatiker2SemExam.Models;

public partial class Opgave
{
    public int Id { get; set; }

    public string Beskrivelse { get; set; }

    public int AnsatId { get; set; }

    public int BilId { get; set; }

    public virtual Ansat Ansat { get; set; }
}