// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Datamatiker2SemExam.Models;

public partial class Treatment
{
    public int Id { get; set; }

    public string Name { get; set; }

    public double Price { get; set; }

    public double? Duration { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Competency> Competencies { get; set; } = new List<Competency>();
}