// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Datamatiker2SemExam.Models;

public partial class User
{
    public int Id { get; set; }

    [Column("username")]
    public string Navn { get; set; }

    [Column("role")]
    public string Rolle { get; set; }

    public string Password { get; set; }
}