// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Datamatiker2SemExam.Models;

public partial class User
{
    public int Id { get; set; }

    public string Navn { get; set; }

    public string Rolle { get; set; }

    public string Password { get; set; }
}